export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = ' REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const CERRAR_SESION= 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
//contacto
export const OBTENER_CONTACTOS = 'OBTENER_CONTACTOS'
export const AGREGAR_CONTACTO = 'AGREGAR_CONTACTO'
export const VALIDAR_CONTACTO = 'VALIDAR_CONTACTO'
export const CONTACTO_ACTUAL = 'CONTACTO_ACTUAL'
export const ELIMINAR_CONTACTO = 'ELIMINAR_CONTACTO'
export const CONTACTO_ERROR  = 'CONTACTO_ERROR'
export const ACTUALIZAR_CONTACTO = 'ACTUALIZAR_CONTACTO'
export const LIMPIAR_CONTACTO = 'LIMPIAR_CONTACTO'

// export const MOSTRAR_USUARIO = 'MOSTRAR_USUARIO'
// export const USUARIO_ACTUAL ='USUARIO_ACTUAL'

//usuario
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO'
export const VALIDAR_USUARIO = 'VALIDAR_USUARIO'
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL'
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO'
export const USUARIO_ERROR  = 'USUARIO_ERROR'
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO'
export const LIMPIAR_USUARIO = 'LIMPIAR_USUARIO'
